version: '2'

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./src/db/sql/initdb:/docker-entrypoint-initdb.d:ro
            - mariadb-data:/var/lib/mysql:rw
        ports:
            - ${MARIADB_PORT}:${MARIADB_PORT}
        environment:
            MYSQL_HOST: ${MARIADB_HOST}
            MYSQL_TCP_PORT: ${MARIADB_PORT}
            MYSQL_USER: ${MARIADB_USER}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MARIADB_NAME}
            SERVICE_NAME: mariadb
            SERVICE_TAGS: dev
        networks:
            - developmentnet

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        command: >
            --requirepass ${REDIS_PASSWORD}
            --bind ${REDIS_IP_LISTEN_FOR_CONNECTIONS_FROM}
            --port ${REDIS_PORT}
            --loglevel ${REDIS_LOGLEVEL}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - redis-data:/usr/local/etc/redis:rw
            - redis-data:/data:rw
        networks:
            - developmentnet

volumes:
    mariadb-data:
    redis-data:

networks:
    developmentnet:
        driver: bridge
